version: "3.8"

services:
  redis:
    image: redis:7-alpine
    ports:
      - '6379:6379'

  postgres:
    image: postgres:latest
    environment:
      - 'POSTGRES_DB=aimuro-conversation-db'
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_PASSWORD=password'
      - 'POSTGRES_HOST_AUTH_METHOD=trust'
    ports:
      - '5433:5432'

  pgvector:
    security_opt:
      - seccomp:unconfined
    image: tsgreenberg1217/gundamhub:gundam-rules-vector-db
    environment:
      - 'POSTGRES_DB=gundam-tcg-rules-vector-db'
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_PASSWORD=password'
      - 'POSTGRES_HOST_AUTH_METHOD=trust'
    labels:
      - "org.springframework.boot.service-connection=postgres"
    ports:
      - '5432:5432'


  gundam-card-db:
    image: tsgreenberg1217/gundamhub:gundam-card-db
    ports:
      - '27017:27017'

  card-service:
    image: gundam-card-service
    ports:
      - '8082:8080'
    environment:
      SPRING_PROFILES_ACTIVE: cloud
      CARD_SERVICE_DB_HOST: gundam-card-db
    depends_on:
        gundam-card-db:
            condition: service_started


  aimuro-service:
    security_opt:
      - seccomp:unconfined
    image: aimuro-service
    depends_on:
      pgvector:
        condition: service_started
      postgres:
        condition: service_started
      redis:
        condition: service_started

    ports:
        - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_DATASOURCE_URL: jdbc:postgresql://pgvector:5432/gundam-tcg-rules-vector-db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: password
      APP_CONVERSATION_DATASOURCE_URL: jdbc:postgresql://postgres:5432/aimuro-conversation-db
      APP_CONVERSATION_DATASOURCE_USERNAME: postgres
      APP_CONVERSATION_DATASOURCE_PASSWORD: password

      SPRING_APPLICATION_NAME: aimuro
      SPRING_LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_HTTP_CONVERTER_JSON: DEBUG
      SPRING_LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_WEB: DEBUG
      SPRING_LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_SECURITY: DEBUG
      SPRING_LOGGING_LEVEL_COM_cardcom_CONTROLLER: DEBUG
      SPRING_LOGGING_LEVEL_COM_cardcom_SERVICE: DEBUG
      SPRING_LOGGING_LEVEL_COM_cardcom_REPOSITORY: DEBUG
      SPRING_LOGGING_LEVEL_COM_FASTERXML_JACKSON_DATABIND: DEBUG
      # AI_VECTORSTORE_PGVECTOR_INITIALIZE_SCHEMA: true
      OPEN_AI_KEY: ${OPEN_AI_KEY}
      MODEL: o4-mini
      SPRING_DATA_REDIS_HOST: redis
      SPRING_DATA_REDIS_PORT: 6379
      GUNDAM_CARD_SERVICE_URL: http://card-service:8080/graphql
